server:
  port: 8188
spring:
  application:
    name: guest-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/guest
    username: postgres
    password: password
    flyway:
      schemas: guest
      user: postgres
      password: password
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost



